[options]
HoldPkg = pacman glibc
Architecture = auto
Color
CheckSpace
ParallelDownloads = 10

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

[cachyos]
Server = https://mirror.cachyos.org/repo/$arch
Server = https://repo.cachyos.org/repo/$arch
SigLevel = Optional TrustAll
